name: Build and Test

on:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

permissions:
  contents: read

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
      - name: Update submodule
        working-directory: ./backend
        run: git submodule init && git submodule update
      - name: Setup Gradle
        working-directory: ./backend
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
      - name: Execute Gradle build
        working-directory: ./backend
        run: gradle assemble
      - name: Run project test suite
        working-directory: ./backend
        run: gradle test
