name: Gradle Build

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
      - name: Execute Gradle build
        run: gradle assemble
      - name: Run project test suite
        run: gradle test
