name: Frontend Build/Tests
on:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

jobs:
  build_with_lint_and_run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Begin job
        uses: actions/checkout@v3

      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      
      - name: Install dependencies
        working-directory: ./gilded-rose-llc-frontend
        run: yarn install --frozen-lockfile

      - name: Run ESLint
        working-directory: ./gilded-rose-llc-frontend
        run: yarn lint

      -name: Run Tests
        working-directory: ./gilded-rose-llc-frontend
        run: yarn test --no-watch
